services:
  - type: web
    name: discord-clone
    runtime: node
    plan: free
    buildCommand: npm install && npm rebuild --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
